name: Track Profile Views

on:
  schedule:
    # Run at midnight UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-views:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          pip install requests pillow matplotlib
          
      - name: Track views and generate graph
        run: python track_views.py
        
      - name: Check for changes
        run: |
          git status
          ls -la
          
      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add view_data.json view_graph.svg
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "[AUTO] Update profile views data"
            git push
          fi